student_data=[
    {
        "name":"sanjay",
        "age":24,
        "course":"py"
    },
    {
       "name":"jay",
        "age":24,
        "course":"py"
    },  
]
a={
    "name":"ay",
    "age":24,
    "course":"py"
}
student_data.append(a   )
print(student_data)